version: 2
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - 9f:ec:85:68:11:4c:06:89:2b:89:46:44:67:b3:fa:f6
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/Picoo_T.M && git pull'

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
